apiVersion: v1
kind: Pod
metadata:
  name: redis-storage-ofir
spec:
  containers:
  - name: redis-storage-ofir
    image: redis:alpine
    volumeMounts:
    - name: redis-persistent-storage
      mountPath: /data/redis
  volumes:
  - name: redis-persistent-storage
    emptyDir: {}