apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: use-pv
  name: use-pvspec
spec:
  containers:
    - name: use-pv
      image: nginx
      volumeMounts:
        - mountPath: "/data"
          name: pv-1
  volumes:
    - name: pv-1
      hostPath:
        path: "/tmp"
  dnsPolicy: ClusterFirst
  restartPolicy: Always