apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-design-pod-1
  labels:
    env: prod
    app: nginx-design-pod-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-design-pod-1
  template:
    metadata:
      labels:
        env: prod
        app: nginx-design-pod-1
    spec:
      containers:
      - name: nginx-design-pod-1
        image: nginx:alpine
        ports:
        - containerPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-design-pod-2
  labels:
    env: dev
    app: nginx-design-pod-2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-design-pod-2
  template:
    metadata:
      labels:
        env: dev
        app: nginx-design-pod-2
    spec:
      containers:
      - name: nginx-design-pod-2
        image: nginx:alpine
        ports:
        - containerPort: 80
